default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: fundfashion_development

test:
  <<: *default
  database: fundfashion_test

production:
  <<: *default
  database: fundfashion_production
  host: ec2-107-22-175-206.compute-1.amazonaws.com
  port: 5432

